In [17]:
#初识pytorch
import torch
import time
import numpy as np

In [29]:
a = torch.randn(100000,1000)
b = torch.randn(1000,200)
t1 = time.time()
c = torch.matmul(a,b)
t2 = time.time()
print(a.device, t2 - t1,c.norm(2))

cpu 0.47161293029785156 tensor(1.00000e+05 *
       1.4146)


In [19]:
torch.tensor([2,3])

tensor([ 2,  3])

In [30]:
#numpy
q = np.array([2.3,3,3])
p = np.ones([2,3])
torch.from_numpy(p)
torch.from_numpy(q)

tensor([ 2.3000,  3.0000,  3.0000], dtype=torch.float64)

In [44]:
#list tensor只有一个参数
torch.tensor([1,2])
torch.tensor([[1,2,3],[2,3,4]])

tensor([[ 1,  2,  3],
        [ 2,  3,  4]])

In [41]:
#uninitialized
torch.empty(2)
torch.Tensor([1,2])#Tensor有多个参数时表示size
torch.IntTensor(2,3,4)

tensor([ 1.,  2.])

In [48]:
#rand
a = torch.rand(2,3)
torch.rand_like(a)
torch.randint(1,10,[3,3])

tensor([[ 7.,  4.,  7.],
        [ 7.,  7.,  7.],
        [ 1.,  9.,  9.]])

In [50]:
#randn normal
torch.randn(2,3)
torch.normal(torch.full([10],0),torch.arange(1,0,-0.1))

tensor([-1.4664, -1.4393,  0.3113,  0.0418, -0.9252, -0.5408,  0.1768,
         0.2163,  0.0543,  0.0079])

In [52]:
#full
torch.full([10],7)
torch.full([2,3],7)

tensor([[ 7.,  7.,  7.],
        [ 7.,  7.,  7.]])

In [55]:
#arange range包含end arange不包含end
torch.arange(1,10)
torch.arange(1,10,2)

tensor([ 1.,  3.,  5.,  7.,  9.])

In [57]:
torch.range(0,10)

tensor([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,
         10.])

In [59]:
torch.set_default_tensor_type(torch.DoubleTensor)

In [63]:
#linspace logspace
torch.linspace(0,10,steps=4)
#tensor([  0.0000,   3.3333,   6.6667,  10.0000])
torch.logspace(0,10,steps=4)#10的多少次方

tensor([ 1.0000e+00,  2.1544e+03,  4.6416e+06,  1.0000e+10])

In [70]:
#ones zeros
torch.ones([3,3])
torch.zeros([3,3])
torch.eye(3,4)

tensor([[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]])

In [73]:
#randperm
torch.randperm(10)#range之后再shuffle

tensor([ 9,  2,  8,  4,  0,  5,  1,  6,  7,  3])

In [81]:
#索引和切片
a = torch.Tensor(4,3,28,28)
a[...,:26].shape
a[:,2:,:,:].shape

torch.Size([4, 1, 28, 28])

In [91]:
#index_select
b = torch.Tensor(4,3,28,28)
b.index_select(0,torch.tensor([0,2])).shape
b.index_select(2,torch.arange(10).long()).shape

torch.Size([4, 3, 10, 28])

In [107]:
#select by mask 铺平之后为1的index对应的地方取值
c = torch.randn(4,3,28,28)
mask = c.ge(0.5)
torch.masked_select(c,mask).shape
torch.take(c,torch.tensor([2,5,8]))

tensor([ 0.3718, -0.1371,  0.0823])

In [110]:
#rand是生成均匀分布,而randn是生成均值为0,方差为1的正态分布
d = torch.rand([4,1,28,28])
d.view(4,28*28)#会丢失size信息


tensor([[ 0.0344,  0.4071,  0.3144,  ...,  0.2210,  0.5305,  0.1221],
        [ 0.9722,  0.1233,  0.3962,  ...,  0.9356,  0.0811,  0.5428],
        [ 0.8182,  0.6977,  0.6539,  ...,  0.4520,  0.7846,  0.1675],
        [ 0.4451,  0.8995,  0.9440,  ...,  0.6989,  0.8162,  0.9940]])

In [ ]:
#squeeze 和 unsqueeze
e = torch.rand([4,1,28,28])
torch.